In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.ensemble import RandomForestClassifier

c:\program files\python3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
def print_confusion_matrix(y_test, y_predict):
    mat = confusion_matrix(y_test, y_predict)
    print("Matriz de confusão: \n"+str(mat))

In [3]:
def  print_score(x_test, y_test, classifier):
    acuracia = classifier.score(x_test, y_test)
    print("Acurácia: "+str(acuracia*100)+"%")

In [4]:
clientes = pd.read_csv('clientes.csv', sep=';')

In [5]:
clientes['ticket_medio'] = (clientes['valor_total_ticket'] / clientes['recorrencia']).round(decimals=2)

clientes.drop(columns=['valor_total_ticket', 'recorrencia', 'cliente'], inplace=True)

In [6]:
treino = clientes.dropna()

In [7]:
y_treino = treino['perfil']
x_treino = treino.drop(columns=['perfil'])

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x_treino, y_treino, test_size=0.3, random_state=0)

In [9]:
#KNN CLASSIFIER
knnClassifier = KNeighborsClassifier(n_neighbors=3) 
knnClassifier.fit(x_train, y_train)
y_predict = knnClassifier.predict(x_test)

In [10]:
y_predict = knnClassifier.predict(x_test)

In [11]:
print("------------------------- KNN -------------------------")
print_confusion_matrix(y_test, y_predict)
print("")
print_score(x_test, y_test, knnClassifier)
print("------------------------- KNN -------------------------")

------------------------- KNN -------------------------
Matriz de confusão: 
[[15  0  0]
 [ 0 51 12]
 [ 0 11 61]]

Acurácia: 84.66666666666667%
------------------------- KNN -------------------------


In [12]:
#RANDOM FOREST CLASSIFIER
classifier = RandomForestClassifier(n_estimators = 100)
classifier = classifier.fit(x_train, y_train)
y_predict = classifier.predict(x_test)

In [13]:
print("------------------------- RANDOM FOREST -------------------------")
print_confusion_matrix(y_test, y_predict)
print("")
print_score(x_test,y_test, classifier)
print("------------------------- RANDOM FOREST -------------------------")

------------------------- RANDOM FOREST -------------------------
Matriz de confusão: 
[[15  0  0]
 [ 0 58  5]
 [ 0 10 62]]

Acurácia: 90.0%
------------------------- RANDOM FOREST -------------------------


In [14]:
cliente_final = clientes[ clientes['perfil'].isnull() ]
cliente_final= cliente_final.drop(columns='perfil')

In [15]:
y_predict_final = classifier.predict(cliente_final)

In [16]:
cliente_final['perfil'] = y_predict_final

cliente_final = cliente_final.append(treino, sort=True)

In [18]:
cliente_final.to_csv('resultado.csv', sep=';')